---
name: PR-sync-to-develop

on:
  pull_request:
    types: [opened, closed]
    branches: ['main', 'main-*']

jobs:
  sync-to-develop:
    name: Sync To Develop branch
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Calculate sync, develop and main branches
        id: calculate-branches
        run: |
          BASELINE_BRANCH=${{ github.base_ref }}
          DEVELOP_BRANCH=${BASELINE_BRANCH/main/develop}
          {
            echo "DEVELOP_BRANCH=$DEVELOP_BRANCH"
            echo "SYNC_BRANCH=automated/sync-from-$BASELINE_BRANCH-to-$DEVELOP_BRANCH"
            echo "MAIN_BRANCH=$BASELINE_BRANCH"
          } >> "$GITHUB_OUTPUT"
      - name: Print values
        id: print-values
        run: |
          echo "DEVELOP_BRANCH=${{ steps.calculate-branches.outputs.DEVELOP_BRANCH }}"
          echo "SYNC_BRANCH=${{ steps.calculate-branches.outputs.SYNC_BRANCH }}"
          echo "MAIN_BRANCH=${{ steps.calculate-branches.outputs.MAIN_BRANCH }}"
